language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
env:
  - CHEF_VERSION="= 0.10.10"
  - CHEF_VERSION="= 10.24.0"
  - CHEF_VERSION="~> 10.0"
  - CHEF_VERSION="= 11.4.0"
  - CHEF_VERSION="~> 11.0"
